<ul class="clip-color-list">
	<li style="width:8.5%;"><a href="javascript:void(0)" ref="none.jpg"><img  src="assets/images/src/clipart/none.jpg"/></a></li>
	<li><a href="javascript:void(0)" ref="Alien.png"><img  src="assets/images/src/clipart/Alien.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Anchor.png"><img  src="assets/images/src/clipart/Anchor.png"/></a></li>	
	<li><a href="javascript:void(0)" ref="Angel.png"><img  src="assets/images/src/clipart/Angel.png"/></a></li>	
	<li><a href="javascript:void(0)" ref="Apple.png"><img  src="assets/images/src/clipart/Apple.png"/></a></li>	
	<li><a href="javascript:void(0)" ref="Attention.png"><img  src="assets/images/src/clipart/Attention.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Badge.png"><img  src="assets/images/src/clipart/Badge.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Baseball.png" ><img  src="assets/images/src/clipart/Baseball.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Basketball.png"><img  src="assets/images/src/clipart/Basketball.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Batman.png"><img  src="assets/images/src/clipart/Batman.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Bear.png"><img  src="assets/images/src/clipart/Bear.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Beers.png"><img  src="assets/images/src/clipart/Beers.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Ball.png"><img  src="assets/images/src/clipart/Bell.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Bike.png"><img  src="assets/images/src/clipart/Bike.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Birdhead.png"><img  src="assets/images/src/clipart/Birdhead.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Bug.png"><img  src="assets/images/src/clipart/Bug.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Butterfly.png"><img  src="assets/images/src/clipart/Butterfly.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Butterfly-1.png"><img  src="assets/images/src/clipart/Butterfly-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Butterfly-2.png"><img  src="assets/images/src/clipart/Butterfly-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Butterfly-3.png"><img  src="assets/images/src/clipart/Butterfly-3.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cabin.png"><img  src="assets/images/src/clipart/Cabin.png"/></a></li>
	<li><a href="javascript:void(0)" ref="CandyCane.png"><img  src="assets/images/src/clipart/CandyCane.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cat-1.png"><img  src="assets/images/src/clipart/Cat-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cat-2.png"><img  src="assets/images/src/clipart/Cat-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cat-3.png"><img  src="assets/images/src/clipart/Cat-3.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Clover.png"><img  src="assets/images/src/clipart/Clover.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cross-1.png"><img  src="assets/images/src/clipart/Cross-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cross-2.png"><img  src="assets/images/src/clipart/Cross-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Cross-3.png"><img  src="assets/images/src/clipart/Cross-3.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Crown.png"><img  src="assets/images/src/clipart/Crown.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Danger.png"><img  src="assets/images/src/clipart/Danger.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Devil.png"><img  src="assets/images/src/clipart/Devil.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Diamond.png"><img  src="assets/images/src/clipart/Diamond.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Diamond-2.png"><img  src="assets/images/src/clipart/Diamond-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Diamond-3.png"><img  src="assets/images/src/clipart/Diamond-3.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Dove.png"><img  src="assets/images/src/clipart/Dove.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Duck.png"><img  src="assets/images/src/clipart/Duck.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Eagle.png"><img  src="assets/images/src/clipart/Eagle.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Earth.png"><img  src="assets/images/src/clipart/Earth.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Eye.png"><img  src="assets/images/src/clipart/Eye.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Female.png"><img  src="assets/images/src/clipart/Female.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Fish.png"><img  src="assets/images/src/clipart/Fish.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Fish-1.png"><img  src="assets/images/src/clipart/Fish-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Flower-1.png"><img  src="assets/images/src/clipart/Flower-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Flower-2.png"><img  src="assets/images/src/clipart/Flower-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Flower-8.png"><img  src="assets/images/src/clipart/Flower-8.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Flower-12.png"><img  src="assets/images/src/clipart/Flower-12.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Foot.png"><img  src="assets/images/src/clipart/Foot.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Football.png"><img  src="assets/images/src/clipart/Football.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Frog-2.png"><img  src="assets/images/src/clipart/Frog-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Girl-1.png"><img  src="assets/images/src/clipart/Girl-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Girl-2.png"><img  src="assets/images/src/clipart/Girl-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Golf-2.png"><img  src="assets/images/src/clipart/Golf-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Graduates.png"><img  src="assets/images/src/clipart/Graduates.png"/></a></li>
	<li><a href="javascript:void(0)" ref="GrimReaper.png"><img  src="assets/images/src/clipart/GrimReaper.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Guitar.png"><img  src="assets/images/src/clipart/Guitar.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Hand-2.png"><img  src="assets/images/src/clipart/Hand-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Heart-1.png"><img  src="assets/images/src/clipart/Heart-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Heart-4.png"><img  src="assets/images/src/clipart/Heart-4.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Heart-5.png"><img  src="assets/images/src/clipart/Heart-5.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Hockey.png"><img  src="assets/images/src/clipart/Hockey.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Horse.png"><img  src="assets/images/src/clipart/Horse.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Horse-1.png"><img  src="assets/images/src/clipart/Horse-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Horse-2.png"><img  src="assets/images/src/clipart/Horse-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="HorseShoe.png"><img  src="assets/images/src/clipart/HorseShoe.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Love.png"><img  src="assets/images/src/clipart/Love.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Male.png"><img  src="assets/images/src/clipart/Male.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Maple.png"><img  src="assets/images/src/clipart/Maple.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Music.png"><img  src="assets/images/src/clipart/Music.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Note.png"><img  src="assets/images/src/clipart/Note.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Paw.png"><img  src="assets/images/src/clipart/Paw.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Paws.png"><img  src="assets/images/src/clipart/Paws.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Peace.png"><img  src="assets/images/src/clipart/Peace.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Plane-1.png"><img  src="assets/images/src/clipart/Plane-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Plus.png"><img  src="assets/images/src/clipart/Plus.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Poison.png"><img  src="assets/images/src/clipart/Poison.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Puzzle.png"><img  src="assets/images/src/clipart/Puzzle.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Race.png"><img  src="assets/images/src/clipart/Race.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Racing.png"><img  src="assets/images/src/clipart/Racing.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Recycle.png"><img  src="assets/images/src/clipart/Recycle.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Ribbon.png"><img  src="assets/images/src/clipart/Ribbon.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Ribbon-1.png"><img  src="assets/images/src/clipart/Ribbon-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Ribbon-2.png"><img  src="assets/images/src/clipart/Ribbon-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Rock-1.png"><img  src="assets/images/src/clipart/Rock-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="SafetyPin.png"><img  src="assets/images/src/clipart/SafetyPin.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Shark.png"><img  src="assets/images/src/clipart/Shark.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Ship-Wheel.png"><img  src="assets/images/src/clipart/Ship-Wheel.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Smile-1.png"><img  src="assets/images/src/clipart/Smile-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Smile-3.png"><img  src="assets/images/src/clipart/Smile-3.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Smile-4.png"><img  src="assets/images/src/clipart/Smile-4.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Soccer.png"><img  src="assets/images/src/clipart/Soccer.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Star-1.png"><img  src="assets/images/src/clipart/Star-1.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Star-2.png"><img  src="assets/images/src/clipart/Star-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Star-4.png"><img  src="assets/images/src/clipart/Star-4.png"/></a></li>
	<li><a href="javascript:void(0)" ref="StarofDavid.png"><img  src="assets/images/src/clipart/StarofDavid.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Superman-2.png"><img  src="assets/images/src/clipart/Superman-2.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Swim.png"><img  src="assets/images/src/clipart/Swim.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Tree.png"><img  src="assets/images/src/clipart/Tree.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Umbrella.png"><img  src="assets/images/src/clipart/Umbrella.png"/></a></li>
	<li><a href="javascript:void(0)" ref="US-Flag.png"><img  src="assets/images/src/clipart/US-Flag.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Weed.png"><img  src="assets/images/src/clipart/Weed.png"/></a></li>
	<li><a href="javascript:void(0)" ref="Yingyang.png"><img  src="assets/images/src/clipart/Yingyang.png"/></a></li>
</ul>