<ul class="font-style-list">
	<li><a href="javascript:void(0)" data-font-name="aardvark_cafe.TTF" ref="Aarvarkcafe.png"><img  src="assets/images/src/fonts/Aarvarkcafe.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Adobe_Garamond_Bold.otf" ref="Adobegaramondbold.png"><img  src="assets/images/src/fonts/Adobegaramondbold.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Air_Stream.TTF" ref="Airstream.png"><img  src="assets/images/src/fonts/Airstream.png"/></a></li>	
	<li><a href="javascript:void(0)" data-font-name="AkzidenzGroteskBQ-Cnd.otf" ref="Akzidenzgroteskbq-reg.png"><img  src="assets/images/src/fonts/Akzidenzgroteskbq-reg.png"/></a></li>	
	<li><a href="javascript:void(0)" data-font-name="Aldo_PC.ttf" ref="Aldosemibold.png"><img  src="assets/images/src/fonts/Aldosemibold.png"/></a></li>	
	<li><a href="javascript:void(0)" data-font-name="ANDY-BOLD.TTF" ref="Anybold.png"><img  src="assets/images/src/fonts/Anybold.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="ARIAL-BLACK.ttf" ref="Arialblack.png"><img  src="assets/images/src/fonts/Arialblack.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="arial-narrow.TTF" ref="Arialnarrow.png" ><img  src="assets/images/src/fonts/Arialnarrow.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="ARIAL-BOLD.ttf" ref="Arialold.png"><img  src="assets/images/src/fonts/Arialold.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="ARLRDBD.TTF" ref="Arialrounded.png"><img  src="assets/images/src/fonts/Arialrounded.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="ArnoPro-Regular.otf" ref="Arnopro.png"><img  src="assets/images/src/fonts/Arnopro.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Artbrush.ttf" ref="Artbrush.png"><img  src="assets/images/src/fonts/Artbrush.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Bauhaus.ttf" ref="Bauhaus.png"><img  src="assets/images/src/fonts/Bauhaus.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BEACHTYP.TTF" ref="BeachTypeMedium.png"><img  src="assets/images/src/fonts/BeachTypeMedium.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="beansfont.ttf" ref="Beans.png"><img  src="assets/images/src/fonts/Beans.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="beatsvil.ttf" ref="Beatsvilleregular.png"><img  src="assets/images/src/fonts/Beatsvilleregular.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BELLBOTT.TTF" ref="Bellbuttom.png"><img  src="assets/images/src/fonts/Bellbuttom.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BRLNSR.TTF" ref="Berlinsansfb.png"><img  src="assets/images/src/fonts/Berlinsansfb.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BlackWolf.ttf" ref="Blackwolf.png"><img  src="assets/images/src/fonts/Blackwolf.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BLADRMF_.TTF" ref="BLADERUNNERMOVIE.png"><img  src="assets/images/src/fonts/BLADERUNNERMOVIE.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Boisterb.ttf" ref="Boisterblack.png"><img  src="assets/images/src/fonts/Boisterblack.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="BOOKOS.TTF" ref="Bookmanoldstyle.png"><img  src="assets/images/src/fonts/Bookmanoldstyle.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Candara.ttf" ref="Candara.png"><img  src="assets/images/src/fonts/Candara.png"/></a></li>
	<!--- <li><a href="javascript:void(0)" data-font-name="" ref="Centurygothic.png"><img  src="assets/images/src/fonts/Centurygothic.png"/></a></li>--->
	<li><a href="javascript:void(0)" data-font-name="CHERI___.TTF" ref="Cheri.png"><img  src="assets/images/src/fonts/Cheri.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="CHOWFUN.TTF" ref="Chowfun.png"><img  src="assets/images/src/fonts/Chowfun.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Chunkfive.otf" ref="Chunkfive.png"><img  src="assets/images/src/fonts/Chunkfive.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="college.ttf" ref="COLLEGE.png"><img  src="assets/images/src/fonts/COLLEGE.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Colony-Wars.ttf" ref="COLONYWARS.png"><img  src="assets/images/src/fonts/COLONYWARS.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="comic_0.ttf" ref="Comicsansms.png"><img  src="assets/images/src/fonts/Comicsansms.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="CooperBlackStd.otf" ref="Cooperblack.png"><img  src="assets/images/src/fonts/Cooperblack.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Creepers.ttf" ref="CREEPERS.png"><img  src="assets/images/src/fonts/CREEPERS.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Decker.ttf" ref="Decker.png"><img  src="assets/images/src/fonts/Decker.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="denmark.ttf" ref="Denmark.png"><img  src="assets/images/src/fonts/Denmark.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="dirty-bakers-dozen.ttf" ref="DIRTYBAKERSDOZEN.png"><img  src="assets/images/src/fonts/DIRTYBAKERSDOZEN.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="EASTMARK.TTF" ref="Eastmarket.png"><img  src="assets/images/src/fonts/Eastmarket.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="ELEPHNT.TTF" ref="Elephant.png"><img  src="assets/images/src/fonts/Elephant.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="FINALOLD.TTF" ref="FinalFrontieroldstyle.png"><img  src="assets/images/src/fonts/FinalFrontieroldstyle.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="framd.ttf" ref="Franklingothicmedium.png"><img  src="assets/images/src/fonts/Franklingothicmedium.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="freedomfighter.ttf" ref="FREEDOMFIGHTER.png"><img  src="assets/images/src/fonts/FREEDOMFIGHTER.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="FREESCPT.TTF" ref="Freestylescript.png"><img  src="assets/images/src/fonts/Freestylescript.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Garamond-Regular.ttf" ref="Garamond.png"><img  src="assets/images/src/fonts/Garamond.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="" ref="Haettenschweiler.png"><img  src="assets/images/src/fonts/Haettenschweiler.png"/></a></li>
	<!--- <li><a href="javascript:void(0)" data-font-name="" ref="Harrington.png"><img  src="assets/images/src/fonts/Harrington.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Hotrod.png"><img  src="assets/images/src/fonts/Hotrod.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Nextstar.png"><img  src="assets/images/src/fonts/Nextstar.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Ringer.png"><img  src="assets/images/src/fonts/Ringer.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Sfplanetaryorbiter.png"><img  src="assets/images/src/fonts/Sfplanetaryorbiter.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Spaceage.png"><img  src="assets/images/src/fonts/Spaceage.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Spacepontiff.png"><img  src="assets/images/src/fonts/Spacepontiff.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Terminaldosisregular.png"><img  src="assets/images/src/fonts/Terminaldosisregular.png"/></a></li>
		  <li><a href="javascript:void(0)" data-font-name="" ref="Timepiece.png"><img  src="assets/images/src/fonts/Timepiece.png"/></a></li>
	--->
	<li><a href="javascript:void(0)" data-font-name="hotpizza.ttf" ref="Hotpizza.png"><img  src="assets/images/src/fonts/Hotpizza.png"/></a></li>	
	<li><a href="javascript:void(0)" data-font-name="impact_0.ttf" ref="Impact.png"><img  src="assets/images/src/fonts/Impact.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="kingrichard.ttf" ref="Kingrichard.png"><img  src="assets/images/src/fonts/Kingrichard.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="KOMIKABG.ttf" ref="Komikaboogie.png"><img  src="assets/images/src/fonts/Komikaboogie.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="lucon_0.ttf" ref="Lucidaconsole.png"><img  src="assets/images/src/fonts/Lucidaconsole.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="metalstorm.ttf" ref="Metalstorm.png"><img  src="assets/images/src/fonts/Metalstorm.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="METROLOX.ttf" ref="Metrolox.png"><img  src="assets/images/src/fonts/Metrolox.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="MTCORSVA.TTF" ref="Monotypecorsiva.png"><img  src="assets/images/src/fonts/Monotypecorsiva.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="MyriadPro-Regular.otf" ref="Myriadpro.png"><img  src="assets/images/src/fonts/Myriadpro.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="NickelodeonNF.ttf" ref="Nikelodeon.png"><img  src="assets/images/src/fonts/Nikelodeon.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Pacifico.ttf" ref="Pacifico.png"><img  src="assets/images/src/fonts/Pacifico.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="pala_0.ttf" ref="Palatinolinotype.png"><img  src="assets/images/src/fonts/Palatinolinotype.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="PermanentMarker.ttf" ref="Permanentmarker.png"><img  src="assets/images/src/fonts/Permanentmarker.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="SCRIPTBL.TTF" ref="Scriptmtstd.png"><img  src="assets/images/src/fonts/Scriptmtstd.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="SHOWG.TTF" ref="Showcardgothic.png"><img  src="assets/images/src/fonts/Showcardgothic.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="SpookyMagic.ttf" ref="Spookymagic.png"><img  src="assets/images/src/fonts/Spookymagic.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Swagger.ttf" ref="Swagger.png"><img  src="assets/images/src/fonts/Swagger.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="tahoma_0.ttf" ref="Tahoma.png"><img  src="assets/images/src/fonts/Tahoma.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="times_0.ttf" ref="Timesroman.png"><img  src="assets/images/src/fonts/Timesroman.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="transfrm.ttf" ref="Transformersmovie.png"><img  src="assets/images/src/fonts/Transformersmovie.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="trebuc_0.ttf" ref="Trebuchetms.png"><img  src="assets/images/src/fonts/Trebuchetms.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="trekker-two-regular-1361513282.ttf" ref="Trekkertwo.png"><img  src="assets/images/src/fonts/Trekkertwo.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="tristan.ttf" ref="Tristan.png"><img  src="assets/images/src/fonts/Tristan.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Tweedledee-Bold.ttf" ref="Tweedledee.png"><img  src="assets/images/src/fonts/Tweedledee.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="Victorian-LET.ttf" ref="Victorianlet.png"><img  src="assets/images/src/fonts/Victorianlet.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="WantedM54.ttf" ref="Wantedms4.png"><img  src="assets/images/src/fonts/Wantedms4.png"/></a></li>
	<li><a href="javascript:void(0)" data-font-name="WickedScaryMovie.ttf" ref="Wickedscarymovie.png"><img  src="assets/images/src/fonts/Wickedscarymovie.png"/></a></li>
</ul>